### ISSUE TITLE
Cant find the API Server code

### ISSUE THREAD

**Issue by nata11** [pro-react/kanban-app#10]
Hello Cassio,
Excellent book. Tried other tutorials and found this is the best for me. 
I cannot find the API Server code as mentioned in Chapter 3 on your Github page. I did find the online server (http://kanbanapi.pro-react.com) but would rather like to run locally.
Thanks

**Comment by cassiozen** [comment]
Hi @nata11 

Thanks for the feedback. A Ruby version of the server is available here: https://github.com/cassiozen/kanban-closed-api-server

If the books is useful for you, could you please leave a feedback at amazon? Thanks.

**Comment by cassiozen** [comment]
Additionaly, user @spolnik was kind enough to share his node.js server for the kanban app: https://github.com/spolnik/node-workspace/tree/master/kanban-board/server
