### ISSUE TITLE
figure 1-7

### ISSUE THREAD

**Issue by brw31415** [pro-react/kanban-app#13]
i wanted to duplicate the figure 1-7, i cut and paste the code from the book  pages 14-20  onto the file structure of original  kanban app, (of course deleting original code ) leaving webpack config alone. The original kanban_app code runs fine, but when i make that change I get:
Uncaught  range error KeyEscapeUtils ...   Maximum call stack exceeded

ie this is the app.js file (exactly as in book) 

import React from 'react';
import {render} from 'react-dom';
import KanbanBoard from './KanbanBoard';

let cardsList = [
  {
     id: 1,
     title: "Read the Book",
     description: "I should read the whole book",
     status: "in-progress",
     tasks: []
  },
  {
     id: 2,
     title: "Write some code",
     description: "Code along with the samples in the book",
     status: "todo",
     tasks: [
       {
          id: 1,
          name: "ContactList Example",
          done: true
       },
       {
          id: 2,
          name: "Kanban Example",
          done: false
       },
       {
          id: 3,
          name: "My own experiments",
          done: false
       }
     ]
  },
];

render(<KanbanBoard cards={cardsList} />, document.getElementById('root'));

**Comment by brw31415** [comment]
immediately before this error, i get:

Warning each child in an array or iterator should have a unique key property. Check render method of 'List'

**Comment by brw31415** [comment]
please disregard, i got it running by fetching the chapter 1 code, which i at first didn' know how to use,
however i still dont understand the reasons for this error

**Comment by cassiozen** [comment]
No problem. Looking your code, it looks like your render call (last line) was incomplete.

**Comment by brw31415** [comment]
thanks, by the way, outside of k&r  this is the best written computer
programming book i've read, carefully planned, etc, maybe could use a bit
smaller chunks in places
