### ISSUE TITLE
Uncaught ReferenceError: update is not defined

### ISSUE THREAD

**Issue by NelsonRock** [pro-react/kanban-app#15]
Hi, update methot in chapter 3 it's not working, method deleteTask in update obejct  is not global even with babel-polyfill imported.

Thank so much.!

**Comment by cassiozen** [comment]
Hi @NelsonRock 

Update is part of the react-addons-update package. Have you tried installing and importing it?

**Comment by NelsonRock** [comment]
Hi @cassiozen ;
Thanks so much for answer!
You are right; i'had not imported update method from react-addons-update but installing yes!
Thanks a lot and good work!
Keep going!

**Comment by cassiozen** [comment]
😄
