### ISSUE TITLE
Ids in local app don't match those retrieved from API

### ISSUE THREAD

**Issue by BenPiggot** [pro-react/kanban-app#16]
I'm not really sure why this happening, but I am fetching card and task id from the /tasks endpoint that don't match the ids as they are configured at the endpoint. So, when I go to delete or update tasks, I get a 404 error.

For example, the 'to do' card has an id of 1865 in my local app, but the simply hitting the endpoint in my browser returns json showing the 'to do' card with an id of 1797. 

Does anyone have any idea why this might be happening?

**Comment by BenPiggot** [comment]
So I just found my error - exact same error as bidhan-a from earlier! I was passing the headers in as a string and not a constant, hence the mismatch between my local ids (my own ids) and the API ids (the public ids everyone gets)

By the way, really enjoying this book so far!

**Comment by cassiozen** [comment]
Great, glad you found the problem.
