### ISSUE TITLE
getting Uncaught SyntaxError: Unexpected token export with contants.js

### ISSUE THREAD

**Issue by BobWalsh** [pro-react/kanban-app#17]
trying to implement chapter4 in my own app, and getting an error if I 1) create file, 2) import it.

**constants.js:
export default {
  CARD: 'card'
};

Referenced in list.js:
import constants from './constants';

I'm building a rails/react app, using ES6 via babel. Any suggestions?

**Comment by cassiozen** [comment]
Hi @BobWalsh , what error are you getting?

**Comment by BobWalsh** [comment]
constants.self-2b3813d….js?body=1:1 Uncaught SyntaxError: Unexpected token export

**Comment by BobWalsh** [comment]
figured it out: needed to be in this form to work:

module.exports = {
  KANBANDECK: 'kanbandeck'
};
