### ISSUE TITLE
Where can I download the stylesheets from?

### ISSUE THREAD

**Issue by joetidee** [pro-react/kanban-app#19]
Where can I download the stylesheets (and other files) that I need for the Kanban app?

**Comment by cassiozen** [comment]
It's all on this repo. You need the checkout the correct chapter on the branch list:

<img width="489" alt="screenshot 2016-09-19 17 53 27" src="https://cloud.githubusercontent.com/assets/33676/18648875/f320e03a-7e92-11e6-8b0b-fed5e283a02e.png">
