### ISSUE TITLE
Starting application error [Chapter 1]

### ISSUE THREAD

**Issue by JaySpears** [pro-react/kanban-app#2]
i.Steps followed:
1. Cloned down repository.
2. `cd` into root of project.
3. `git fetch --all`
4. `git checkout chapter1`
5. `npm install` (Was successfull)<br>
   <img width="412" alt="screen shot 2016-01-13 at 9 57 13 pm" src="https://cloud.githubusercontent.com/assets/9599633/12315456/a8bf30f8-ba40-11e5-97b6-937d80bcbcf0.png">
6. 'npm start' (Seems to have worked properly)<br>
   <img width="337" alt="screen shot 2016-01-13 at 9 51 23 pm" src="https://cloud.githubusercontent.com/assets/9599633/12315466/c1c455f6-ba40-11e5-824e-3aed922e6f87.png">

<br>ii.Issues:
1. Going to the local environment: `http://localhost:8080/` (Getting empty response).
   <img width="621" alt="screen shot 2016-01-13 at 9 53 23 pm" src="https://cloud.githubusercontent.com/assets/9599633/12315406/23a8bfce-ba40-11e5-8173-2c14f2e374b0.png">

Any ideas why? 
The `npm start` command has the right paths, I doubled checked. 
I even deleted the repository and cloned it down again to see if I installed it wrong the first time. Same issue is happening.

**Comment by JaySpears** [comment]
So.. I cant view this project at `localhost:8080`, but I can view it at `127.0.0.1`. 
I have `127.0.0.1` as `localhost` in my `/etc/hosts` file..

**Comment by cassiozen** [comment]
Hi Josh,

I'm glad it works @ 127.0.0.1 
Which OS are you using? What's the node version you have installed?

**Comment by JaySpears** [comment]
Im using Yosemite. I haven't upgraded to El Capitan yet. Im using 4.4.1 version of node. Why do you ask?

**Comment by cassiozen** [comment]
Just to try to understand what could have happened...

**Comment by JaySpears** [comment]
It was one of those wonky things.
