### ISSUE TITLE
How can I download the KanbanBoard sample source for the book 'React.JS'?

### ISSUE THREAD

**Issue by tudoistube** [pro-react/kanban-app#22]
Hi, I am about to start learning React.js according to the book 'ProReact' written by Cassio de Sousa Antonio.
For building a basic understanding on environment, I firstly reviewed its appendix on the book.
Then I returned to the first chapter.
I managed to practice HelloWorld and GroceryList examples.
I got sample sources at the following urls:
$ git clone https://github.com/pro-react/kanban-app.git
$ git clone https://github.com/pro-react/sample-code.git
$ git clone https://github.com/pro-react/pro-react.github.io.git
$ git clone https://github.com/pro-react/react-app-advanced-boilerplate.git
$ git clone https://github.com/pro-react/react-app-boilerplate.git

but I could not find a full example sources about Kanban.
When I cloned with  '$ git clone https://github.com/pro-react/kanban-app.git',
I only found 4 files : .gitignore, LICENSE, README.md files and .git directory.

Please show me how to get a full sample sources for studying Kanban App in this book?

Thank you in advance.

**Comment by ghost** [comment]
I have the same issue, maybe the author hasn't had the chance to upload the remaining files, I just went step by step and typed it out. I'm sure the repo will eventually be updated

**Comment by tudoistube** [comment]
I captured some images for your references, but I can not find a function to upload images.
I managed to find sample sources here anyhow.
You can find "9 branches" in the middle section of this github(https://github.com/pro-react/kanban-app).
Then click the link of "9 branches" and you can find sample sources in each chapter.
You can view each sample sources.
In my case I could not git clone because I faced 'Permission Denied' and failed to follow its solution at the end of the document(https://help.github.com/articles/generating-an-ssh-key/).
I hope you have obtained sample sources and please let me know if you know any solutions about permission denied.
I attached an images by dragging and dropping.
![githubusage_](https://cloud.githubusercontent.com/assets/9345140/17841207/3ff068f2-6851-11e6-886a-010f51f5b46b.jpg)
![githubusage_ 2](https://cloud.githubusercontent.com/assets/9345140/17841236/79c1eb96-6851-11e6-9fac-079064ee71bc.jpg)
![githubusage_ 3](https://cloud.githubusercontent.com/assets/9345140/17841237/79d0af14-6851-11e6-81ee-7e25a9c18e58.jpg)

**Comment by ghost** [comment]
thanks for the info, I too got permission denied when trying to clone. If I do come across the sample sources, I'll put a link in this thread.

**Comment by tudoistube** [comment]
Since I posted this question here, I have studied gitHub and used my repository without problem nowadays.
But I 'm still wondering why I can not fetch or clone this repository...
This morning I tried fetching chapter3 repository as belows quotation, but failed by permission denied.
Please tell me if anyone knows what I missed doing...
Thanks in advance.
//---------------------------------------------------------------------------------------------------------------

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit
$ git init
Initialized empty Git repository in D:/WSpace_React_Tutorial/zproreact2/zgit/.git/

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (master)
$ git checkout -b chapter3
Switched to a new branch 'chapter3'

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (chapter3)
$ git remote add origin git@github.com:pro-react/kanban-app.git

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (chapter3)
$ git remote -v
origin  git@github.com:pro-react/kanban-app.git (fetch)
origin  git@github.com:pro-react/kanban-app.git (push)

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (chapter3)
$ git fetch origin chapter3
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:blablabla....
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,###.##.###.###' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (chapter3)
$ git fetch origin chapter3
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (chapter3)
$ git clone git@github.com:pro-react/kanban-app.git
Cloning into 'kanban-app'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

erp03@erp03-PC MINGW32 /d/WSpace_React_Tutorial/zproreact2/zgit (chapter3)
$

**Comment by tudoistube** [comment]
I got a solution how to download a sample source!
Answer is fork!
'git clone' still does not work as below the 1st capture image.
But I tried fork, fetch and merge it, then I got the source at my notebook ^ ^
Now I enter into Kanban with routing at Chapter5.
I also backup my practice source into my github.
Hope to study together ^ ^!!!

![git_source_clone](https://cloud.githubusercontent.com/assets/9345140/18570569/1709ff22-7be6-11e6-8d62-da93df2be35f.jpg)
![git_source_fork](https://cloud.githubusercontent.com/assets/9345140/18570570/170b8630-7be6-11e6-90d8-3eef7fbd27f7.jpg)
