### ISSUE TITLE
POST request not working in Kanban API server

### ISSUE THREAD

**Issue by bidhan-a** [pro-react/kanban-app#3]
Not sure if it's only me but I can't add new tasks in the app. The server returns a 500 Error. Toggling and Deleting tasks work just fine however.

**Comment by bidhan-a** [comment]
Nevermind. It was a silly mistake on my part. I was passing API_HEADERS as a string('API_HEADERS') instead of passing it as a constant.

**Comment by cassiozen** [comment]
:+1:
