### ISSUE TITLE
ch4 / KanbanBoardContainer.js - Two .bind() needed

### ISSUE THREAD

**Issue by dxps** [pro-react/kanban-app#4]
Hi Cássio,

A small update at the end of [KanbanBoardContainer.js](https://github.com/pro-react/kanban-app/blob/chapter4/app/KanbanBoardContainer.js) on chapter 4 is needed.
In `cardCallbacks` prop, only `persistCardDrag` contains `.bind(this)` at the end.

As such, moving a card will throw the standard error of 'cards is undefined', since the calling context is wrong. So, `KanbanBoardContainer.js` should end like this:

```
    render() {

        return ( <KanbanBoard
                      cards={this.state.cards}
                      taskCallbacks={{ ... }}
                      cardCallbacks={{
                        updateStatus: this.updateCardStatus.bind(this),
                        updatePosition: this.updateCardPosition.bind(this),
                        persistCardDrag: this.persistCardDrag.bind(this)
                      }}
                  />
        )
    }

}

export default KanbanBoardContainer;
```

Last, but not least, thank you very much for the book! :-)

**Comment by cassiozen** [comment]
Thanks for the feedback, and I'm glad you're enjoying it.

Wanna make a pull request? If you don't feel like doing so, I will update asap.

**Comment by dxps** [comment]
I hope it's ok. You may find [here](https://github.com/pro-react/kanban-app/pull/5) the details.
