### ISSUE TITLE
FETCH_CARDS_FAILURE const typo

### ISSUE THREAD

**Issue by schraj** [pro-react/kanban-app#7]
Awesome book. thanks!

Small typo that causes the action message to be incorrect in the FetchCards call in the Chapter 6-Flux branch.

Currently:

  FETCH_CARDS: 'fetch cards',
  FETCH_CARDS_SUCCESS: 'fetch cards success',
  FETCH_CARDS_SUCCESS: 'fetch cards error',

Should be:

  FETCH_CARDS: 'fetch cards',
  FETCH_CARDS_SUCCESS: 'fetch cards success',
  FETCH_CARDS_FAILURE: 'fetch cards error',

Jeremy

**Comment by cassiozen** [comment]
Thanks @schraj  - just fixed it.
