### ISSUE TITLE
There is no more pro-react/kanban-api-server

### ISSUE THREAD

**Issue by spolnik** [pro-react/kanban-app#9]
Could you please provide sources to kanban api server please?

**Comment by cassiozen** [comment]
Hi @spolnik - 
The sources for the kanban-api are in Ruby on Rails. They're available here: https://github.com/cassiozen/kanban-closed-api-server

I was expecting to port it to Node before moving to Pro-React's github group.

**Comment by spolnik** [comment]
I see, I've already written down node version to progress with book:
https://github.com/spolnik/node-workspace/tree/master/kanban-board/server maybe you will find some parts useful (it's using nedb, to give optionality for persistence).

Thanks,
Jacek

**Comment by cassiozen** [comment]
Very cool, @spolnik. Are you doing all the book exercises in TypeScript?

**Comment by spolnik** [comment]
Yes, I prefer it over babel. With types/interfaces/generics - it's making it much easier to write apps - appreciated it during Kanban App development - as it was helping me on compile time ;)

**Comment by cassiozen** [comment]
How did you implement the card sorting?

**Comment by spolnik** [comment]
This is not implemented yet, so far I didn't find straightforward way to do it on nedb
